# Kak-Bundle Plugin Loader
source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle "https://codeberg.org/jdugan6240/kak-bundle"

# Plugins
bundle kakboard "https://github.com/lePerdu/kakboard" %{
      hook global WinCreate .* %{ kakboard-enable }
}

bundle auto-pairs.kak "https://github.com/alexherbo2/auto-pairs.kak" %{
  enable-auto-pairs
}

bundle modeline-extras https://github.com/basbebe/modeline-extras.kak %{
  set-option global modeline-nerdfont true

  # enable options
  modeline-buffer-position-enable
  modeline-git-branch-enable
  modeline-indent-enable
  modeline-lsp-enable

  # Git branch + Filename
  set-option global modelinefmt '{magenta+i}%opt{modeline_git_branch} {bright-blue+u}%val{bufname}{default}'
  # Position
  set-option -add global modelinefmt ' %val{cursor_line}:%val{cursor_char_column} %opt{modeline_buffer_position}{default}'
  # Context Info + Mode Info
  set-option -add global modelinefmt ' {{context_info}} {{mode_info}}'
  # lsp
  set-option -add global modelinefmt ' {DiagnosticError}%opt{modeline_lsp_err}{DiagnosticWarning}%opt{modeline_lsp_warn}{default}'
  # Filetype + Indentwidth
  set-option -add global modelinefmt ' %opt{filetype} %opt{modeline_indent}'
  # client@session
  set-option -add global modelinefmt ' {bright-cyan}%val{client}{bright-cyan+b}%val{session}'
}

# statusline
set-option global modelinefmt '%val{bufname} '
set-option -add global modelinefmt '{comment}%sh{ [ -n "$kak_opt_filetype" ] && printf "($kak_opt_filetype) "}'
set-option -add global modelinefmt '%val{cursor_line}:%val{cursor_char_column} '
set-option -add global modelinefmt '{default}{{context_info}} {{mode_info}} - %val{client}'

bundle fzf.kak "https://github.com/andreyorst/fzf.kak" %{
  map global normal <c-p> ': fzf-mode<ret>'
  map global user f ': fzf-mode<ret>' -docstring 'Fuzzy Find'
}

bundle kak-lsp "https://github.com/kak-lsp/kak-lsp" %{
  lsp-enable
  map global user l ': enter-user-mode lsp<ret>' -docstring 'LSP'
  set-option global lsp_auto_highlight_references true
  set-option global lsp_hover_max_lines 20
  set-option global lsp_hover_anchor true

  lsp-inlay-diagnostics-enable global
  lsp-auto-signature-help-enable

  declare-option -hidden str lsp_modeline_progress ""
    define-command -hidden -params 6 -override lsp-handle-progress %{
      set-option global lsp_modeline_progress %sh{
        if ! "$6"; then
          echo "$2${5:+" ($5%)"}${4:+": $4"}"
        fi
      }
   }
}

source "%val{config}/colemak.kak"
source "%val{config}/cursor.kak"

# Config

colorscheme ef-dream

set global tabstop 2
set global indentwidth 2

# set global autoinfo normal

# Scroll Margin
set-option global scrolloff 12,3

# Set Terminal Assistant
set-option global ui_options terminal_assistant=cat

add-highlighter global/ number-lines -relative
# add-highlighter global/bar column 80 ,rgba:ffffff88

# Tab Autocompletion
hook global InsertCompletionShow .* %{
  map window insert <tab> <c-n>
  map window insert <s-tab> <c-p>
}

hook global InsertCompletionHide .* %{
  map window insert <tab> <c-n>
  map window insert <s-tab> <c-p>
}

# Case Insensitive Search
map global normal '/' '/(?i)'

# Buffer Mode
declare-user-mode buffer-mode
map global user b ": enter-user-mode buffer-mode<ret>" -docstring "Buffers"
map global buffer-mode b " fb" -docstring "fuzzy picker"
map global buffer-mode p ":buffer-previous<ret>" -docstring "previous buffer"
map global buffer-mode n ":buffer-next<ret>" -docstring "next buffer"
map global buffer-mode k ":delete-buffer<ret>" -docstring "kill buffer"

# TMUX Mode
declare-user-mode tmux-mode
map global user t ": enter-user-mode tmux-mode<ret>" -docstring "TMUX"
map global tmux-mode h ": tmux-repl-vertical<ret>" -docstring "horizontal split"
map global tmux-mode v ": tmux-repl-horizontal<ret>" -docstring "vertical split"
map global tmux-mode t ": tmux-repl-window<ret>" -docstring "new window"

# FZF Mode
hook global ModuleLoaded fzf %{
  map global fzf k "<esc>:e ~/.config/kak/kakrc<ret>" -docstring "open kakrc"
  map global fzf m "<esc>:tmux-repl-window yazi<ret>" -docstring "manage files"
}
