#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super+Shift Return spawn footclient

# Super+Shift F to start a floating terminal seperate from the foot server
riverctl map normal Super+Shift F spawn "foot --app-id=float-term -W 100x40 -e fish"

# Super+D to open dmenu
riverctl map normal Super D spawn fuzzel

# Super+W to open firefox
riverctl map normal Super W spawn firefox-esr

# Super+L to lock
riverctl map normal Super L spawn swaylock

# Super+Shift+Q to close the focused view
riverctl map normal Super+Shift Q close

# Super+Shift+Control+C to exit river
riverctl map normal Super+Shift+Control C exit

# Super+N and Super+E to focus the next/previous view in the layout stack
riverctl map normal Super N focus-view next
riverctl map normal Super E focus-view previous

# Super+Shift+N and Super+Shift+E to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift N swap next
riverctl map normal Super+Shift E swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+I to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super I send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+I to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift I send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,N,E,I} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt N move down 100
riverctl map normal Super+Alt E move up 100
riverctl map normal Super+Alt I move right 100

# Super+Alt+Control+{H,N,E,I} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control N snap down
riverctl map normal Super+Alt+Control E snap up
riverctl map normal Super+Alt+Control I snap right

# Super+Alt+Shift+{H,N,E,I} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift N resize vertical 100
riverctl map normal Super+Alt+Shift E resize vertical -100
riverctl map normal Super+Alt+Shift I resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set keyboard layout
riverctl keyboard-layout -variant "colemak" -options "ctrl:nocaps" "us"

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all windows use ssd by default
riverctl rule-add ssd

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Focus follows Cursor
riverctl focus-follows-cursor normal

# Hide Cursor when typing
riverctl hide-cursor when-typing enabled

# Set Cursor Theme
riverctl xcursor-theme BreezeX-RosePine-Linux 32

# Set River Theme
source ~/.config/river/theme

### TOUCHPAD
riverctl input "pointer-1739-0-Synaptics_tm2964-001" tap enabled
riverctl input "pointer-1739-0-Synaptics_tm2964-001" natural-scroll enabled
riverctl input "pointer-1739-0-Synaptics_tm2964-001" disable-while-typing enabled

### SPAWNS
riverctl spawn "/usr/libexec/pipewire-launcher"
riverctl spawn "foot --server"
riverctl spawn "swaybg -i ~/Pictures/.wallpaper.jpg --mode fill"
riverctl spawn "wlsunset -S 07:00 -s 22:00"
riverctl spawn "waybar"
riverctl spawn "dunst"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
