# THEME
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Set Shell to TMUX 
[shell]
program = "/usr/bin/tmux"
args = ["new", "-As0"]

# WINDOW
[window]
blur = true
dynamic_padding = true
dynamic_title = true
opacity = 1.0
title = "Terminal"

# FONT
[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 12.0

# COLORS
[colors]
draw_bold_text_with_bright_colors = true

# CURSOR
[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_timeout = 0

# MOUSE
[mouse]
hide_when_typing = true

# [extra]
# Add the following lines to your configuration file to set the keybindings for Tab with Control and Control+Shift:
[keyboard]
bindings = [
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
    { key = "F11", action = "ToggleFullscreen" },
]
